### ISSUE TITLE
Fix the managing about and introduction from NetlifyCMS 

### ISSUE THREAD

**Issue by caseyjkey** [caseyjkey/gatsby-portfolio-with-blog#8]
When attempting to modify the about and introduction sections, there are list widgets that contain objects. These objects aren't rendered properly and instead display No undefined and a string widget labeled undefined. 

This is the current buggy config.yml

```
backend:
  name: github
  repo: caseykey/caseykey.github.io
  branch: source
  site_domain: quirky-bassi-7f760a.netlify.com

site_url: https://caseyjkey.com
display_url: https://caseyjkey.com

public_folder: "/src/images/"
media_folder: "/src/images/"

collections:
  - label: "Sections"
    name: "sections"
    files:
    - label: "Introduction"
      name: "introduction"
      file: "src/data/introduction.json"
      fields:
        - {label: "Greeting", name: "greeting", widget: "string", default: "Hey! I am"}
        - {label: "Name", name: "name", widget: "string", default: "Casey Key"}
        - label: "Descriptions"
          label_singular: "description"
          name: "descriptions"
          widget: "list" 
          field:
            - label: "Description"
              name: "description"
              widget: "object"
              fields:
                - {label: "Description", name: "header", widget: "string"}
                - {label: "Example", name: "subheader", widget: "string"} 
    - label: "About Me"
      name: "about"
      file: "src/data/about.json"
      fields:
        - {label: Bio, name: bio, widget: text, default: "I was born and raised in West Philadelphia. On the basketball court is where I spent most of my days; maxin', relaxin', actin' all cool, when some guys who were up to no good, started trouble in my neighborhood."}
        - label: "Activities"
          label_singular: "Activity"  
          name: "activities"
          widget: "list"
          field:
            - label: "Icon"
              name: "icon"
              widget: "object"
              fields:
                - {label: "Font Awesome", name: "fa", label_singular: 'Font Awesome icon', widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
                - {label: "Devicons", name: "di", label_singular: 'Devicon', widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
                - {label: "Ionicons", name: "io", label_singular: 'Ionicon', widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
            - {label: "Description", name: description, widget: string, default: 'CS and ENTR @ CSU, FoCo'}

  - label: "Projects" # Used in the UI
    name: "projects" # Used in routes, e.g., /admin/collections/blog
    label_singular: 'Project'
    folder: "src/data/projects" # The path to the file where projects are defined
    path: "{{slug}}/project"
    slug: "{{project}}"
    media_folder: 'images' # Should save images in same directory as the project, to make referencing easier
    create: true
    extension: json
    format: json
    fields: # The fields for each document, usually in front matter
      - {label: "Project Name", name: "project", widget: "string", hint: "A project name used for files and folders", pattern: ['^[\w\-]+$', "Accepted characters are alphanumeric, _, and -."]}
      - {label: "Image", name: "image", widget: "image", allow_multiple: false}
      - label: "Gallery"
        name: "galleryImages"
        label_singular: 'image'
        widget: "list"
        fields:
        - {label: "Image", name: "image", widget: "image"}
      - {label: "Start Date", name: "start", widget: "datetime", timeformat: false, dateFormat: "MMMM YYYY", format: "MMMM YYYY"}
      - label: "End Date"
        name: "end"
        widget: "object"
        fields:
        - {label: "Present", name: "present", widget: "boolean", default: false, hint: "Toggle on if project's in development.", required: false}
        - {label: "Completed", name: "date", widget: "datetime", timeformat: false, dateFormat: "MMMM YYYY", format: "MMMM YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - label: "Icons"
        name: "icons"
        widget: "object"
        fields:
          - {label: "Font Awesome", name: "fa", label_singular: 'Font Awesome icon', widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
          - {label: "Devicons", name: "di", label_singular: 'Devicon', widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
          - {label: "Ionicons", name: "io", label_singular: 'Ionicon', widget: "list", field: {label: Icon, name: icon, widget: string}, required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string", required: false}

```
